# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: mkdir build && cd build
      - run: cmake ..
      - run: make -j8
  run-server:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: ./build/server
  run-client:
    machine:
      image: ubuntu-2204:2023.10.1
    steps:
      - checkout
      - run: ./build/client
  


# Orchestrate jobs using workflows
# See: https://circleci.com/docs/configuration-reference/#workflows
workflows:
  build-and-run:
    jobs:
      - build
      - run-server
      - run-client
